# Generated by Django 3.2.24 on 2024-02-21 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cqal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Update2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Info', models.CharField(blank=True, max_length=600, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='update1',
            name='Info',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
