# Generated by Django 3.2.24 on 2024-02-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cqal', '0002_auto_20240221_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Update3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Info', models.CharField(blank=True, max_length=600, null=True)),
            ],
        ),
    ]
